#!/bin/bash

avconv -re -loop 1 -i tfw.png -r 25 \
-thread_queue_size 512 -f alsa -i default -fflags +genpts \
-vcodec h264 \
-preset ultrafast -pix_fmt yuv420p -s 1024x768 \
-c:a aac -b:a 10k -ar 44100 \
-f flv out.flv
